baseURL = "/"
languageCode = "fr"
summaryLength = "10"
theme = "kross-hugo"
title = "Loïc Viard-Crétat portfolio"
[menu]
main = []
[params]
address = "35 avenue du docteur Chavent 73400 Ugine"
author = "Johnathan Smith"
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = ""
email = "loicviard12@gmail.com"
google_analitycs_id = ""
home = "Home"
logo = ""
phone = "07 50 57 81 87"
social = []
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
